			LinkedItems[{
				MenuItem["None", CellDingbat->None, Scope->SelectionCell],
				Delimiter,
				MenuItem["Filled Square",		CellDingbat->"\[FilledSquare]",			Scope->SelectionCell],
				MenuItem["Gray Square",			CellDingbat->"\[GraySquare]",			Scope->SelectionCell],
				MenuItem["Empty Square",		CellDingbat->"\[EmptySquare]",			Scope->SelectionCell],
				MenuItem["Dotted Square",		CellDingbat->"\[DottedSquare]",			Scope->SelectionCell],
				MenuItem["Filled Small Square",	CellDingbat->"\[FilledSmallSquare]",	Scope->SelectionCell],
				MenuItem["Empty Small Square",	CellDingbat->"\[EmptySmallSquare]",		Scope->SelectionCell],
				Delimiter,
				MenuItem["Filled Circle",		CellDingbat->"\[FilledCircle]",			Scope->SelectionCell],
				MenuItem["Gray Circle",			CellDingbat->"\[GrayCircle]",			Scope->SelectionCell],
				MenuItem["Empty Circle",		CellDingbat->"\[EmptyCircle]",			Scope->SelectionCell],
				MenuItem["Filled Small Circle",	CellDingbat->"\[FilledSmallCircle]",	Scope->SelectionCell],
				MenuItem["Empty Small Circle",	CellDingbat->"\[EmptySmallCircle]",		Scope->SelectionCell],
				Delimiter,
				MenuItem["Filled Diamond",		CellDingbat->"\[FilledDiamond]",		Scope->SelectionCell],
				MenuItem["Empty Diamond",		CellDingbat->"\[EmptyDiamond]",			Scope->SelectionCell],
				MenuItem["Filled Up Triangle",	CellDingbat->"\[FilledUpTriangle]",		Scope->SelectionCell],
				MenuItem["Empty Up Triangle",	CellDingbat->"\[EmptyUpTriangle]",		Scope->SelectionCell],
				MenuItem["Filled Down Triangle",CellDingbat->"\[FilledDownTriangle]",	Scope->SelectionCell],
				MenuItem["Empty Down Triangle",	CellDingbat->"\[EmptyDownTriangle]",	Scope->SelectionCell],
				Delimiter,
				MenuItem["Watch",				CellDingbat->"\[WatchIcon]",			Scope->SelectionCell],
				MenuItem["Filled Star",			CellDingbat->"\[FivePointedStar]",		Scope->SelectionCell],
				MenuItem["Happy Smiley",		CellDingbat->"\[HappySmiley]",			Scope->SelectionCell],
				MenuItem["Neutral Smiley",		CellDingbat->"\[NeutralSmiley]",		Scope->SelectionCell],
				MenuItem["Sad Smiley",			CellDingbat->"\[SadSmiley]",			Scope->SelectionCell],
				MenuItem["Light Bulb",			CellDingbat->"\[LightBulb]",			Scope->SelectionCell],
				MenuItem["Wolf",				CellDingbat->"\[Wolf]",					Scope->SelectionCell],
				Delimiter,
				MenuItem["Club Suit",			CellDingbat->"\[ClubSuit]",				Scope->SelectionCell],
				MenuItem["Diamond Suit",		CellDingbat->"\[DiamondSuit]",			Scope->SelectionCell],
				MenuItem["Heart Suit",			CellDingbat->"\[HeartSuit]",			Scope->SelectionCell],
				MenuItem["Spade Suit",			CellDingbat->"\[SpadeSuit]",			Scope->SelectionCell]
			}];(**)