	MenuItem["50%", Magnification->0.50, Scope->NotebookDefault];(**)
    MenuItem["75%", Magnification->0.75, Scope->NotebookDefault];(**)
    MenuItem["100%", Magnification->1.00, Scope->NotebookDefault];(**)
    MenuItem["125%", Magnification->1.25, Scope->NotebookDefault];(**)
    MenuItem["150%", Magnification->1.50, Scope->NotebookDefault];(**)
    MenuItem["200%", Magnification->2.00, Scope->NotebookDefault];(**)
    MenuItem["300%", Magnification->3.00, Scope->NotebookDefault];(***)